include("${CMAKE_CURRENT_LIST_DIR}/Platforms/${CMAKE_SYSTEM_NAME}Config.cmake")

list(APPEND KITSUNE_GLOBAL_INCLUDE_DIRECTORIES
    "${KITSUNE_ROOT_DIR}/Source/Runtime"
)

if (CMAKE_CONFIGURATION_TYPES)
    list(APPEND KITSUNE_GLOBAL_COMPILER_DEFINITIONS
        "KITSUNE_BUILD_$<UPPER_CASE:$<CONFIG>>=1"
    )

    list(APPEND KITSUNE_GLOBAL_COMPILER_FLAGS
        "$<$<CONFIG:Debug>:${KITSUNE_DEBUG_COMPILER_FLAGS}>"
        "$<$<CONFIG:Optimized>:${KITSUNE_OPTIMIZED_COMPILER_FLAGS}>"
        "$<$<CONFIG:Production>:${KITSUNE_PRODUCTION_COMPILER_FLAGS}>"
    )

    list(APPEND KITSUNE_GLOBAL_COMPILER_DEFINITIONS
        "$<$<CONFIG:Debug>:${KITSUNE_DEBUG_COMPILER_DEFINITIONS}>"
        "$<$<CONFIG:Optimized>:${KITSUNE_OPTIMIZED_COMPILER_DEFINITIONS}>"
        "$<$<CONFIG:Production>:${KITSUNE_PRODUCTION_COMPILER_DEFINITIONS}>"
    )

    list(APPEND KITSUNE_GLOBAL_LINKER_FLAGS
        "$<$<CONFIG:Debug>:${KITSUNE_DEBUG_LINKER_FLAGS}>"
        "$<$<CONFIG:Optimized>:${KITSUNE_OPTIMIZED_LINKER_FLAGS}>"
        "$<$<CONFIG:Production>:${KITSUNE_PRODUCTION_LINKER_FLAGS}>"
    )
else()
    string(TOUPPER ${CMAKE_BUILD_TYPE} KITSUNE_UPPERCASE_BUILD_TYPE)

    list(APPEND KITSUNE_GLOBAL_COMPILER_DEFINITIONS
        "KITSUNE_BUILD_${KITSUNE_UPPERCASE_BUILD_TYPE}"
    )

    list(APPEND KITSUNE_GLOBAL_COMPILER_FLAGS "${KITSUNE_${KITSUNE_UPPERCASE_BUILD_TYPE}_COMPILER_FLAGS}")
    list(APPEND KITSUNE_GLOBAL_COMPILER_DEFINITIONS "${KITSUNE_${KITSUNE_UPPERCASE_BUILD_TYPE}_COMPILER_DEFINITIONS}")
    list(APPEND KITSUNE_GLOBAL_LINKER_FLAGS "${KITSUNE_${KITSUNE_UPPERCASE_BUILD_TYPE}_LINKER_FLAGS}")

    unset(KITSUNE_UPPERCASE_BUILD_TYPE)
endif()
